apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  namespace: ingress-basic
  name: proshanta-dns-eastus-cloudapp-azure-com-cert-staging
spec:
  secretName: proshanta-dns-eastus-cloudapp-azure-com-staging
  dnsNames:
  - proshanta-dns.eastus.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - proshanta-dns.eastus.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
